### ISSUE TITLE
Logo image help

### ISSUE THREAD

**Issue by Zeke13** [themachinist/mastercam-setup-sheet#3]
How do I link my logo image into the area you've provided?

**Comment by themachinist** [comment]
Hi Zeke, I've added a section to the Wiki describing the process: https://github.com/themachinist/mastercam-setup-sheet/wiki#changing-the-logo

**Comment by Zeke13** [comment]
Thanks David, I had to add a picture to the header, because the the logo spot is just a label that didn't have an image field. I think it's working right...I probably shouldn't be allowed around a keyboard.
